version: "3"
services:
  app:
    build: "."
    depends_on:
      - "db"
    ports:
      - "5000:5000"
    environment:
      - "IP=0.0.0.0"
      - "PORT=5000"
      - "DEBUG=1"
    networks:
      - "app-network"

  db:
    image: "postgres:9.6.2-alpine"
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    env_file: .env
    environment:
      - "POSTGRES_DB=$DB_NAME"
      - "POSTGRES_USER=$DB_USER"
      - "POSTGRES_PASSWORD=$DB_PASS"
    networks:
      - "app-network"

networks:
  app-network:
